on:
  schedule:
  - cron: "0/15 * * * *"
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://leagueboard-production.up.railway.app/api/trpc/summoner.updateSummoners
